SRCS	= srcs/*.c

OBJS	= ${SRCS:.c=.o}

NAME 	= do-op

CC		= gcc
RM		= rm -f

CFLAGS	= -Wall -Wextra -Werror


all:
		${CC} ${CFLAGS} ${SRCS} -o ${NAME}

clean:
			${RM} ${OBJS}

fclean:		clean
			${RM} ${NAME}

re:			fclean all

.PHONY:		all clean fclean re
